# Generated by Django 3.1 on 2020-08-25 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0003_auto_20200824_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlyurl',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlyurl',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
